/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pslms;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.UIManager;

/**
 *
 * @author HP
 */
public class pitch_report extends javax.swing.JFrame {

    Connection conn = null;
    public pitch_report() {
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        }
    
        catch(Exception ee){
            System.out.println(ee);
}
        initComponents();
        conn = PSLMS.connect();
    }
    PreparedStatement pst;
    ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Manage_PitchReport = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Weathers = new javax.swing.JTextField();
        Pitch_Types = new javax.swing.JTextField();
        Pitch_Conditions = new javax.swing.JTextField();
        Due_Factors = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Match_No = new javax.swing.JTextField();
        placs = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Manage_PitchReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pitch Report Management");
        Manage_PitchReport.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        Weathers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeathersActionPerformed(evt);
            }
        });
        Manage_PitchReport.add(Weathers, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 148, -1));

        Pitch_Types.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pitch_TypesActionPerformed(evt);
            }
        });
        Manage_PitchReport.add(Pitch_Types, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 150, -1));

        Pitch_Conditions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pitch_ConditionsActionPerformed(evt);
            }
        });
        Manage_PitchReport.add(Pitch_Conditions, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 150, -1));

        Due_Factors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Due_FactorsActionPerformed(evt);
            }
        });
        Manage_PitchReport.add(Due_Factors, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 150, -1));

        jLabel2.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pitch condition");
        Manage_PitchReport.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, 20));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Place");
        Manage_PitchReport.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pitch Type");
        Manage_PitchReport.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dew factor");
        Manage_PitchReport.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, 20));

        jButton2.setBackground(new java.awt.Color(2, 33, 27));
        jButton2.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Manage_PitchReport.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 550, -1, -1));

        jButton3.setBackground(new java.awt.Color(2, 33, 27));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Match Number");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Manage_PitchReport.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));
        Manage_PitchReport.add(Match_No, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 110, -1));
        Manage_PitchReport.add(placs, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 140, -1));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Weather");
        Manage_PitchReport.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pslms/Pitch (1).png"))); // NOI18N
        Manage_PitchReport.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pslms/psl-with-trophy.png"))); // NOI18N
        Manage_PitchReport.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 620));

        jLabel8.setText("jLabel8");
        Manage_PitchReport.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 530, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Manage_PitchReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Manage_PitchReport, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void WeathersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeathersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WeathersActionPerformed

    private void Pitch_ConditionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pitch_ConditionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pitch_ConditionsActionPerformed

    private void Due_FactorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Due_FactorsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Due_FactorsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PlayersPannel e = new PlayersPannel();
        e.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Pitch_TypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pitch_TypesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pitch_TypesActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         try {      
            pst = conn.prepareStatement("select Match_No, places,Weather,Pitch_Type,Due_Factor,Pitch_Condition from pitch_reports where Match_No=?");
            
            
             
             
            int shirt = Integer.parseInt(Match_No.getText());
			pst.setInt(1, shirt);
			ResultSet rs = pst.executeQuery();
			if(rs.next()==false)
				{
				javax.swing.JOptionPane.showMessageDialog(this, "Sorry Record Not Found");
                                placs.setText("");
                                Weathers.setText("");
                                Pitch_Types.setText("");
                                Due_Factors.setText("");
                                Pitch_Conditions.setText("");
                                
                                
                                Match_No.requestFocus();
			        }
                        else
                        {
                        placs.setText(rs.getString("places"));
			Weathers.setText(rs.getString("Weather"));
                        Pitch_Types.setText(rs.getString("Pitch_Type"));
                        Due_Factors.setText(rs.getString("Due_Factor"));
                        Pitch_Conditions.setText(rs.getString("Pitch_Condition"));
                        
                       
                        
                
		}
            
        } catch (SQLException ex) {
              javax.swing.JOptionPane.showMessageDialog(null, "Reord not saved");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pitch_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pitch_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pitch_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pitch_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pitch_report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Due_Factors;
    private javax.swing.JPanel Manage_PitchReport;
    private javax.swing.JTextField Match_No;
    private javax.swing.JTextField Pitch_Conditions;
    private javax.swing.JTextField Pitch_Types;
    private javax.swing.JTextField Weathers;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField placs;
    // End of variables declaration//GEN-END:variables
}
