/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pslms;

import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author HP
 */
public class player_details extends javax.swing.JFrame {

    Connection conn = null;
     private ImageIcon format= null;
   String fname =null;
   byte[] pimage=null;
    public player_details() {
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        }
    
        catch(Exception ee){
            System.out.println(ee);
}
        initComponents();
        conn = PSLMS.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        player_details = new javax.swing.JPanel();
        name = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Shirt_No = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        playertype = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Runs = new javax.swing.JTextField();
        Wickets = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Run_Rate = new javax.swing.JTextField();
        Strike_Rate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        economy = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblimage = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        player_details.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        player_details.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 100, -1));

        jButton1.setBackground(new java.awt.Color(0, 33, 27));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        player_details.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, -1, -1));
        player_details.add(Shirt_No, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 100, -1));

        jLabel1.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Total Runs/Wickets");
        player_details.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        jLabel2.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Shirt_No");
        player_details.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));
        player_details.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 110, -1));
        player_details.add(playertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 110, -1));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        player_details.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username");
        player_details.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));
        player_details.add(Runs, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 60, -1));
        player_details.add(Wickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 50, -1));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Strike Rate");
        player_details.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));
        player_details.add(Run_Rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 120, -1));
        player_details.add(Strike_Rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 120, -1));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Player Type");
        player_details.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password");
        player_details.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, -1, -1));
        player_details.add(economy, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 110, -1));
        player_details.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 120, -1));

        jLabel8.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Run Rate");
        player_details.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));

        jLabel9.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Economy");
        player_details.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, -1));

        lblimage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        player_details.add(lblimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 170, 160));

        jButton2.setBackground(new java.awt.Color(0, 33, 27));
        jButton2.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Choose image");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        player_details.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 170, -1));

        jLabel11.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Player's Profile");
        player_details.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        jButton3.setBackground(new java.awt.Color(2, 33, 27));
        jButton3.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        player_details.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pslms/psl-with-trophy.png"))); // NOI18N
        player_details.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(player_details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(player_details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String shirt = Shirt_No.getText();
        String names = name.getText();
         String user = username.getText();
          String type = playertype.getText();
          String run = Runs.getText();
          String wicket = Wickets.getText();
          String Rrate = Run_Rate.getText();
          String Srate = Strike_Rate.getText();
          String economys = economy.getText();
          String passwords = password.getText();
          
       
        try{
            String q = "INSERT INTO player_details(Shirt_No,name,username,playertype,Runs,Wickets,Run_Rate,Strike_Rate,economy,password,images)VALUES('"+shirt+"','"+names+"','"+user+"','"+type+"','"+run+"','"+wicket+"','"+Rrate+"','"+Srate+"','"+economys+"','"+passwords+"',?)";
            PreparedStatement demo;
            //            demo = prepareStatement(q);
            demo  =conn.prepareStatement(q);
            demo.setBytes(1, pimage);

            demo.execute();
            JOptionPane.showMessageDialog(null, "Record saved");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Record Not saved     "+e.getLocalizedMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         JFileChooser fchoser=new JFileChooser();
        fchoser.showOpenDialog(null);
        File f=fchoser.getSelectedFile();
        fname=f.getAbsolutePath();
        ImageIcon micon=new ImageIcon(fname);
        try {
            File image=new File(fname);
            FileInputStream fis=new FileInputStream(image);
            ByteArrayOutputStream baos=new ByteArrayOutputStream();
            byte[] buf=new byte[1024];
            for(int readnum; (readnum=fis.read(buf)) !=-1;)
            {
                baos.write(buf,0,readnum);
            }
            pimage=baos.toByteArray();
            lblimage.setIcon(resizeImage(fname, buf));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      Management e = new Management();
        e.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed
 public ImageIcon resizeImage(String imagePath, byte[] pic){

            ImageIcon myImage=null;
            if(imagePath !=null)
            {
                myImage=new ImageIcon(imagePath);

            }else{
                myImage=new ImageIcon(pic);
            }

            Image img=myImage.getImage();
            Image img2=img.getScaledInstance(lblimage.getHeight(),    lblimage.getWidth(),  Image.SCALE_SMOOTH);
            ImageIcon image=new ImageIcon(img2);
            return image;
    }                                        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(player_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(player_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(player_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(player_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new player_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Run_Rate;
    private javax.swing.JTextField Runs;
    private javax.swing.JTextField Shirt_No;
    private javax.swing.JTextField Strike_Rate;
    private javax.swing.JTextField Wickets;
    private javax.swing.JTextField economy;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblimage;
    private javax.swing.JTextField name;
    private javax.swing.JTextField password;
    private javax.swing.JPanel player_details;
    private javax.swing.JTextField playertype;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
