/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pslms;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author jawad
 */
public class Search extends javax.swing.JFrame {

    private ImageIcon format=null;
   String fname=null;
   int s=0;
   byte[] pimage=null;

    Connection conn = null;
    public Search() {
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        }
    
        catch(Exception ee){
            System.out.println(ee);
}
        initComponents();
        conn = PSLMS.connect();
    }
 PreparedStatement pst;
    ResultSet rs;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Search = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Shirt_No = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        type = new javax.swing.JTextField();
        Run = new javax.swing.JTextField();
        Economys = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        Runrate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        names = new javax.swing.JTextField();
        Wicket = new javax.swing.JTextField();
        Strikerate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Search.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search Players");
        Search.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        Shirt_No.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Shirt_No.setForeground(new java.awt.Color(0, 102, 0));
        Shirt_No.setText("Enter Shirt No");
        Shirt_No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Shirt_NoActionPerformed(evt);
            }
        });
        Search.add(Shirt_No, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 202, -1));

        jButton1.setBackground(new java.awt.Color(2, 33, 27));
        jButton1.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        jButton1.setForeground(null);
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Search.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        Search.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total Runs/Wickets");
        Search.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Palyer Type");
        Search.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Economy");
        Search.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, -1));

        type.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        type.setForeground(new java.awt.Color(0, 102, 0));
        Search.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 153, -1));

        Run.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Run.setForeground(new java.awt.Color(0, 102, 0));
        Search.add(Run, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 70, -1));

        Economys.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Economys.setForeground(new java.awt.Color(0, 102, 0));
        Search.add(Economys, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 153, -1));

        jButton2.setBackground(new java.awt.Color(2, 33, 27));
        jButton2.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        jButton2.setForeground(null);
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Search.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, -1, -1));

        Runrate.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Runrate.setForeground(new java.awt.Color(0, 102, 0));
        Search.add(Runrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 153, -1));

        jLabel7.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Run Rate");
        Search.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Search.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 160, 170));

        names.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        names.setForeground(new java.awt.Color(0, 102, 0));
        Search.add(names, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 153, -1));
        Search.add(Wicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 60, -1));

        Strikerate.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Strikerate.setForeground(new java.awt.Color(0, 102, 0));
        Search.add(Strikerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 153, -1));

        jLabel8.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Strike Rate");
        Search.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pslms/PSL-NORMAL-PAGE.png"))); // NOI18N
        Search.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Shirt_NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Shirt_NoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Shirt_NoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          try {      
            pst = conn.prepareStatement("select Shirt_No,name,playertype,Runs,Wickets,Run_Rate,Strike_Rate,economy,images from player_details where Shirt_No=?");
            
            
             
             
            int shirt = Integer.parseInt(Shirt_No.getText());
			pst.setInt(1, shirt);
			ResultSet rs = pst.executeQuery();
			if(rs.next()==false)
				{
				JOptionPane.showMessageDialog(this, "Sorry Record Not Found");
                                names.setText("");
                                type.setText("");
                                Run.setText("");
                                Wicket.setText("");
                                Runrate.setText("");
                                Strikerate.setText("");
                                Economys.setText("");
                                
                                Shirt_No.requestFocus();
			        }
                        else
                        {

                        names.setText(rs.getString("name"));
                        type.setText(rs.getString("playertype"));
			Run.setText(rs.getString("Runs"));
                        Wicket.setText(rs.getString("Wickets"));
                        Runrate.setText(rs.getString("Run_Rate"));
                        Strikerate.setText(rs.getString("Strike_Rate"));
                        Economys.setText(rs.getString("Economy"));
                        
                        byte[] imagedata=rs.getBytes("images");
               format=new ImageIcon(imagedata);
               Image mm=format.getImage();
               Image img2=mm.getScaledInstance(image.getWidth(),        image.getHeight(), Image.SCALE_SMOOTH);
               ImageIcon images=new ImageIcon(img2);
               image.setIcon(images);
                       
                        
                
		}
            
        } catch (SQLException ex) {
              JOptionPane.showMessageDialog(null, "Reord not saved");
        }
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PlayersPannel e = new PlayersPannel();
             e.setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Economys;
    private javax.swing.JTextField Run;
    private javax.swing.JTextField Runrate;
    private javax.swing.JPanel Search;
    private javax.swing.JTextField Shirt_No;
    private javax.swing.JTextField Strikerate;
    private javax.swing.JTextField Wicket;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField names;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables
}
